accelerator: ddp
batch_size: 64
beam_size: 0
checkpoint_every: 5000
clip_grad: 50
config_load: null
config_save: null
d_dropout: 0.2
data_path: ''
data_root: /dccstor/medscan7/smallmolecule/runs/ba-predictor/small-data/affinity
dataset_length: null
dataset_name: sol
debug: true
device: cuda
dropout: 0.1
eval_every: 1000
fast_dev_run: false
fc_h: 512
finetune_path: ''
freeze_model: false
from_scratch: false
gen_save: null
gpus: 8
grad_acc: 1
log_file: null
lr: 0.001
lr_end: 0.00030000000000000003
lr_multiplier: 8
lr_start: 3.0e-05
max_epochs: 4
max_len: 202
measure_name: measure
min_len: 1
mode: cls
model_arch: BERT_16GPU_Both_10percent_rotate_no_masking
model_load: null
model_save: model.pt
model_save_dir: ./models_dump/
n_batch: 1800
n_embd: 768
n_head: 12
n_jobs: 1
n_last: 1000
n_layer: 12
n_samples: null
n_workers: 8
nucleus_thresh: 0.9
num_epoch: 1
num_feats: 32
num_nodes: 1
num_seq_returned: 0
num_workers: 0
pretext_size: 0
q_dropout: 0.5
restart_path: ''
resume: false
root_dir: .
rotate: true
seed: 12345
smiles_embedding: /dccstor/medscan7/smallmolecule/runs/ba-predictor/small-data/embeddings/protein/ba_embeddings_tanh_512_2986138_2.pt
tb_loc: null
train_load: both
unlike_alpha: 1.0
unlikelihood: false
use_linear: 0
val_load: null
vocab_load: null
vocab_save: null
